baseURL = "https://njkevlani.github.io/"
theme = "hst"
enableEmoji = true
enableGitInfo = true

[author]
  name = "Nilesh Kevlani"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 2

  [[menu.main]]
    name = "TILs"
    url = "/tils/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    name = "Links"
    url = "/links/"
    weight = 5

[taxonomies]
  tag = "tags"
  blogtag = "blogtags"
  tiltag = "tiltags"

[permalinks]
  blogtags = "/blogs/tags/:slug"
  tiltags = "/tils/tags/:slug"

[outputs]
    section = ["HTML"]
    taxonomyTerm = ["HTML"]
    taxonomy = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

[markup]

  [markup.goldmark]

    [markup.goldmark.extensions]
      typographer = false

    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    lineNos = true
    style = 'autumn'

