baseURL = "https://njkevlani.dev"
languageCode = 'en-us'
relativeURLs = true
enableEmoji = true
enableGitInfo = true

[params.author]
  name = "Nilesh Kevlani"

[params]
  [params.postHistory]
    enabled = true
    siteGitRepo = "https://github.com/njkevlani/njkevlani.github.io"
    contentDirRelativeToGitRepoRoot = "content"

[frontmatter]
  lastmod = ["lastmod", ":git"]

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  # [[menu.main]]
  #   name = "Writings"
  #   url = "/writings/"
  #   weight = 2

  # [[menu.main]]
  #   name = "Tags"
  #   url = "/tags/"
  #   weight = 3

  [[menu.main]]
    name = "Knowledge Base"
    url = "/kb/"
    weight = 4
    [menu.main.params]
      icon = "/assets/icons/external-link.svg"
      target = "_blank"

  [[menu.main]]
    name = "Resume"
    url = "/resume/"
    weight = 5
    [menu.main.params]
      icon = "/assets/icons/external-link.svg"
      target = "_blank"

[taxonomies]
  tag = "tags"

[outputs]
    section = ["HTML"]
    taxonomy = ["HTML"]
    term = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

[markup]

  [markup.goldmark]

    [markup.goldmark.extensions]
      typographer = false

    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    lineNos = true
    style = 'autumn'

